### ISSUE TITLE
custom_types and documents not pushed to created repository + prismic endpoint misconfigured 

### ISSUE THREAD

**Issue by JulioJu** [prismicio-community/nuxt-sm-tutorial-series#2]
Hi 

Thanks for your quick start explained at https://prismic.io/docs/technologies/run-a-pre-configured-project-nuxtjs. 

But contrary to  https://github.com/prismicio/nuxtjs-blog/ : 
* custom_types are not pushed
* documents are not pushed
* prismic endpoint is not configured to the repository created. Compare following : 
  * prismicio/nuxtjs-blog/nuxt.config.js
  ```js
  endpoint: "https://your-repo-name.cdn.prismic.io/api/v2",
  ``` 
  https://github.com/prismicio/nuxtjs-blog/blob/811a73f9f7178b1ff2a820560bc8ed6eb132dd97/nuxt.config.js#L51
  * https://github.com/prismicio-community/nuxt-sm-tutorial-series/blob/d1117ec54011f4efbbe1ddb9b878c36853e46edf/nuxt.config.js#L41

Could you improve this example in this way please :-) ? For the following people, it could be cool 😄 .

Thanks in advance,

**Comment by JulioJu** [comment]
@phillysnow all seems to be fixed by https://github.com/prismicio-community/nuxt-sm-tutorial-series/pull/3 ?

**Comment by phillysnow** [comment]
Yes, all these things shouldn't be an issue, but only if you're using the latest version of the CLI that was pushed today:
https://www.npmjs.com/package/prismic-cli

**Comment by JulioJu** [comment]
Ok thanks @phillysnow :-)

**Comment by JulioJu** [comment]
Works with version 3.x too (tested).

**Comment by JulioJu** [comment]
@phillysnow 

Sorry for ma confusion.

Endpoint is now correctly defined. But custom_types are not automatically populated into prismic.io. I open a new issue.
