### ISSUE TITLE
custom_types are not automatically populated into prismic.io

### ISSUE THREAD

**Issue by JulioJu** [prismicio-community/nuxt-sm-tutorial-series#5]
@phillysnow 

With prismic-cli v***4*** or v***3*** when we run

```
$ prismic theme --theme-url https://github.com/prismicio-community/nuxt-sm-tutorial-series --conf sm.json
```

Nothing is populated into prismic.io. No `custom_types` or no `document`.  Probably it's normal because there is no such folder.

![image](https://user-images.githubusercontent.com/11527844/126238718-5c82296e-5ab8-415c-a713-c1b93aa909dd.png)

======

It could be cool to have at least the same thing than with : 
```
$ prismic theme --theme-url https://github.com/prismicio/nuxtjs-website --conf nuxt.config.js
```

Into https://github.com/prismicio/nuxtjs-website/tree/a2eae05415a62161db7169bc43501030af3f9d43 we could see a folder `custom_types` and `documents` than populate `custom_types` and document into prismic.io.

![image](https://user-images.githubusercontent.com/11527844/126238985-0ebf98d7-edfe-44de-b51d-1dac3b425c7d.png)

**Comment by phillysnow** [comment]
So this is expected behaviour when it comes to Slice Machine sample projects, this is why in the install guide we have step 

> 6. Push your Shared Slices to Prismic

https://prismic.io/docs/technologies/run-a-pre-configured-project-nuxtjs

There are plans to prepopulate content for Slice Machine themes in the future, but it's not being worked on at the minute.

**Comment by JulioJu** [comment]
Ok thanks @phillysnow for your answer :-)

**Comment by phillysnow** [comment]
No worries, although you're right, the custom types should be pushed initially, we're looking into this.

**Comment by JulioJu** [comment]
Ok thanks !

**Comment by phillysnow** [comment]
This should be good now, just upgrade the CLI to 4.0.2

**Comment by JulioJu** [comment]
It works, thanks !
